apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-simulation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-simulation-configmap
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-simulation-configmap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-simulation-configmap
subjects:
  - kind: ServiceAccount
    name: backend-simulation
