# 백엔드 서비스 자동 스케일링 설정 (HPA)
# CPU/메모리 사용률에 따라 Pod 수 자동 조정
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1    # 최소 Pod 수 (시스템 오류 시)
  maxReplicas: 15   # 최대 Pod 수 (긴급 뉴스 시)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # CPU 50% 이상 시 스케일 업 (민감하게)
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60  # 메모리 60% 이상 시 스케일 업
  behavior:
    scaleDown:      # 스케일 다운 정책
      stabilizationWindowSeconds: 60  # 1분 안정화 (빠른 반응)
      policies:
      - type: Percent
        value: 50   # 최대 50% 감소
        periodSeconds: 30
    scaleUp:        # 스케일 업 정책
      stabilizationWindowSeconds: 30   # 30초 안정화 (빠른 증가)
      policies:
      - type: Percent
        value: 100  # 최대 100% 증가
        periodSeconds: 15
