apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
  annotations:
    # ArgoCD Image Updater 설정은 argocd-application.yml에서 일괄 관리
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-pull-secret
      containers:
      - name: frontend
        image: dorrry/k8s-gitops-app-frontend:627f2de
        ports:
        - containerPort: 3001
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
            ephemeral-storage: 50Mi
          limits:
            cpu: 500m
            memory: 256Mi
            ephemeral-storage: 256Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
