---
# GitOps 자동화를 위한 메인 플레이북
# ArgoCD, Image Updater, Monitoring, HPA를 Ansible로 관리
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Master Node
  hosts: masters
  become: yes
  roles:
    - master

- name: Setup Worker Nodes
  hosts: workers
  become: yes
  roles:
    - worker

- name: Deploy ArgoCD
  hosts: masters
  become: yes
  tasks:
    - import_tasks: tasks/argocd.yml
      tags: [argocd, gitops]

- name: Deploy Monitoring Stack
  hosts: masters
  become: yes
  tasks:
    - import_tasks: tasks/monitoring.yml
      tags: [monitoring, prometheus, grafana]

- name: Setup HPA and Metrics Server
  hosts: masters
  become: yes
  tasks:
    - import_tasks: tasks/hpa.yml
      tags: [hpa, autoscaling]

