# 백엔드 CI/CD 파이프라인
# backend/ 폴더 변경 시 자동으로 Docker 이미지 빌드 및 배포
name: Backend CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'    # 백엔드 코드 변경 시 실행
      - 'shared/**'     # 공통 코드 변경 시 실행
      - '.github/workflows/backend-ci.yml' # 이 워크플로우 파일 변경 시 실행
      - 'k8s/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'shared/**'
      - '.github/workflows/backend-ci.yml' # 이 워크플로우 파일 변경 시 실행
      - 'k8s/**'
env:
  DOCKER_IMAGE: dorrry/k8s-gitops-app-backend
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
        
    - name: Image digest
      run: echo "${{ steps.meta.outputs.tags }}"
      
    - name: Update backend deployment image tag
      if: github.ref == 'refs/heads/master'
      run: |
        # Git 설정
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 이미지 태그 추출
        IMAGE_SHA=$(echo "${{ steps.meta.outputs.tags }}" | grep -o '[a-f0-9]\{7\}' | head -1)
        
        # 최대 5번 재시도
        for i in {1..5}; do
          echo "Attempt $i: Updating backend deployment image tag"
          
          # 최신 변경사항 가져오기
          git fetch origin master
          git reset --hard origin/master
          
          # 이미지 태그 업데이트
          sed -i "s|image: .*|image: ${{ env.DOCKER_IMAGE }}:$IMAGE_SHA|g" k8s/backend-deployment.yml
          
          # 변경사항 확인 후 커밋
          if git diff --quiet; then
            echo "No changes to commit for backend"
            break
          fi
          
          git add k8s/backend-deployment.yml
          git commit -m "Auto-deploy backend: Update image to $IMAGE_SHA [skip ci]"
          
          # 푸시 시도
          if git push origin master; then
            echo "Backend deployment updated successfully with image: ${{ env.DOCKER_IMAGE }}:$IMAGE_SHA"
            break
          else
            echo "Push failed, retrying in 10 seconds..."
            sleep 10
          fi
        done
